Repository SOEN341-F24-CodeBusters/PeerAssessmentSystem, pull requests merged in 2024-11, with the labels that each got.

#55 US2-T6 Display the teams that the student is in
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/CreateAccountPage.tsx
  CodebustersPAS-ClientApp/src/pages/LoginPage.tsx
  CodebustersPAS-ClientApp/src/pages/Students/CourseListingStudentsPage.css
  CodebustersPAS-ClientApp/src/pages/Students/PeerAssessment.jsx
  CodebustersPAS-ClientApp/src/pages/Students/TeamItem.jsx
  CodebustersPAS-ClientApp/vite.config.ts
  CodebustersPAS-Server/API/Controllers/StudentController.cs
Labels: task, User Story 2

#78 BUG Duplicate students when uploading a CSV
  CodebustersPAS-Server/API/Controllers/TeacherController.cs
Labels: BUG

#104 US7-T1: Created the instructor dashboard page for view of results and linked with TeamOverview
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/CSVUpload.jsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/TeamOverview.css
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/TeamOverview.jsx
  CodebustersPAS-ClientApp/src/pages/Teacher/InstructorDashboard.css
  CodebustersPAS-ClientApp/src/pages/Teacher/InstructorDashboard.tsx
Labels: User Story 7

#105 Bug hotfix GitHub pages
  CodebustersPAS-ClientApp/index.html
  CodebustersPAS-ClientApp/public/404.html
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/vite.config.ts
Labels: BUG, DevOps

#107 BUG potential duplicate user student during signup
  CodebustersPAS-Server/API/Controllers/AuthentificationController.cs
Labels: BUG

#106 Build and Publish Server Docker Image with Github actions and Dockerfile
  .github/workflows/build-and-publish-server-docker-image.yml
  CodebustersPAS-Server/Dockerfile
  CodebustersPAS-Server/Infrastructure/PeerAssessmentSystemDbContext.cs
Labels: DevOps

#100 US6 T8 connect frontend and backend for student evaluations
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/AssessmentDimension.jsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/GroupEvaluation.jsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/Self-Assessment.jsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/Summary_Comments.tsx
  CodebustersPAS-ClientApp/src/pages/Students/CourseListingStudentsPage.css
  CodebustersPAS-ClientApp/src/pages/Students/PeerAssessment.jsx
  CodebustersPAS-ClientApp/src/pages/Students/TeamItem.jsx
  CodebustersPAS-Server/API/Controllers/StudentController.cs
Labels: task, User Story 6
