Repository SOEN341-F24-CodeBusters/PeerAssessmentSystem, pull requests merged in 2024-10, with the labels that each got.

#54 US1-T8-connect frontend backend
  CodebustersPAS-ClientApp/src/pages/CreateAccountPage.tsx
  CodebustersPAS-ClientApp/src/pages/LoginPage.tsx
  CodebustersPAS-Server/API/Controllers/AuthentificationController.cs
  CodebustersPAS-Server/Infrastructure/Migrations/20240924215557_refactor-database.Designer.cs
  CodebustersPAS-Server/Infrastructure/Migrations/20240924215557_refactor-database.cs
  CodebustersPAS-Server/Infrastructure/Migrations/20240926021508_fix-typo.Designer.cs
  CodebustersPAS-Server/Infrastructure/Migrations/20240926021508_fix-typo.cs
Labels: task, User Story 1

#59 US2-T2-Server Upload CSV
  CodebustersPAS-Server/API/Controllers/TeacherController.cs
Labels: User Story 2

#74 DevOps - Add testing to the client app (frontend)
  .github/workflows/dotnet.yml
  .github/workflows/vite.yml
  CodebustersPAS-ClientApp/package-lock.json
  CodebustersPAS-ClientApp/package.json
  CodebustersPAS-ClientApp/test/setupTests.ts
  CodebustersPAS-ClientApp/test/signIn.test.tsx
  CodebustersPAS-ClientApp/vite.config.ts
Labels: DevOps

#61 US5 Add Navigation bar & Logout for Student and Instructor
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/LogoutButton.tsx
  CodebustersPAS-ClientApp/src/pages/NavBar.css
  CodebustersPAS-ClientApp/src/pages/NavBar.tsx
  CodebustersPAS-ClientApp/src/pages/Students/PeerAssessment.jsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/CreateTeam.css
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/CreateTeamPopup.jsx
Labels: User Story 5

#75 US6-T1 - Setup the peer evaluation page for students -Version 1
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/AssessmentDimension.jsx
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/EvaluationStyles.css
  CodebustersPAS-ClientApp/src/pages/CourseEvaluation/GroupEvaluation.jsx
  CodebustersPAS-ClientApp/src/pages/Students/CourseItem.jsx
Labels: User Story 6

#60 US2-T2-Frontend Import CSV file
  CodebustersPAS-ClientApp/package-lock.json
  CodebustersPAS-ClientApp/package.json
  CodebustersPAS-ClientApp/src/App.tsx
  CodebustersPAS-ClientApp/src/pages/LoginPage.tsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/CSVUpload.jsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/CreateTeam.tsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/TeamOverview.css
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/TeamOverview.jsx
  CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/styles.css
  CodebustersPAS-ClientApp/vite.config.ts
  CodebustersPAS-Server/API/Controllers/AuthentificationController.cs
  CodebustersPAS-Server/API/Controllers/TeacherController.cs
  CodebustersPAS-Server/API/Program.cs
Labels: User Story 2
